### ISSUE TITLE
install commands

### ISSUE THREAD

**Issue by CKoaser** [AF83/koalab#12]
In the install documentation there is probably 1 line missing:

before executing "grunt", bower has to install all the dependencies listet in the brower file. therefore the list should be as follows:

git clone git@github.com:AF83/koalab.git
cd koalab
cp config/server.json.example config/server.json
$EDITOR config/server.json
npm install -g grunt-cli
npm install .
bower install
grunt
node koalab.js
firefox http://localhost:8080/

In our case not executing bower install lead to a reference error by the $ command, as zepto was not available.

One question: could you please provide the version without the mozilla persona authentication, as it works in the demo version on http://koalab.af83.com/ ?

**Comment by nono** [comment]
Hi,

thanks for your message.

For bower install,  it was supposed to be ran by npm, as a postinstall step (cf https://github.com/AF83/koalab/blob/master/package.json#L38). But seems like it doesn't work. So, I've put it in README.

For the demo version, the code is in the repository. It's just a flag in the `config/server.json` file:

```json
{
  "authorized": ["*@af83.com"],
  "demo": true,
  "port": 8080,
  "persona": {
    "audience": "http://koalab.af83.com"
  },
  "mongodb": {
    "host": "localhost",
    "database": "koalab_prod"
  }
}
```
